name: Lint C# Code Base

on:
  workflow_call:

jobs:
  lint:
    name: Perform Lint C# Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@7739b9ba2efcda9dde65ad1e3c2dbe65b41dfba7 # v3.5.3

      - name: Linting C#
        uses: super-linter/super-linter@ab3ef521138772689ab517eae6c677df902dcef6 # v5.2.0
        env:
          VALIDATE_CSHARP: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
