name: Lint C# Code Base

on:
  workflow_call:

jobs:
  lint:
    name: Perform Lint C# Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@4a1e83c9ef6b0e39b16f17b2734e08cdfbeea46c # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v3.5.3

      - name: Linting C#
        uses: super-linter/super-linter@c6eefcfda9aece111497bc708a3aa1566d6479de # v5.2.0
        env:
          VALIDATE_CSHARP: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
