name: Lint C# Code Base

on:
  workflow_call:

jobs:
  lint:
    name: Perform Lint C# Code Base
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@394d78e5b40cc35c170eb909b1f81551f37feb05 # v2.5.0
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.5.3

      - name: Linting C#
        uses: super-linter/super-linter@bc9693bc5e2a15d216351f8939b2f11560ef73f5 # v5.2.0
        env:
          VALIDATE_CSHARP: true
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
